# Generated by Django 6.0.1 on 2026-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Mitjana'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10, verbose_name='Severidad')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado en')),
            ],
            options={
                'verbose_name': 'Incidente de Seguridad',
                'verbose_name_plural': 'Incidentes de Seguridad',
                'ordering': ['-detected_at'],
            },
        ),
    ]
